# Generated by Django 4.2.1 on 2023-09-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_userprofile_parent_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ntn",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="strn",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
