# Generated by Django 4.2.1 on 2023-09-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userprofile_ntn_userprofile_strn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="picture",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="media/logo/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="registration_no",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="social_links",
            field=models.TextField(blank=True, null=True),
        ),
    ]
